"""more fields to mol

Revision ID: 47d2f117c44e
Revises: e1a7eb1b2835
Create Date: 2024-10-08 15:43:15.240227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d2f117c44e'
down_revision = 'e1a7eb1b2835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('publication')

    # ### end Alembic commands ###
