"""Added affiliation to user

Revision ID: 5a2da15b5a3d
Revises: 19432b8f3f06
Create Date: 2024-10-09 11:03:28.196221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2da15b5a3d'
down_revision = '19432b8f3f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation', sa.String(length=120), nullable=True))
        batch_op.drop_column('favourite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('affiliation')

    # ### end Alembic commands ###
