"""added concentration to molecule

Revision ID: bc08064c981f
Revises: e646fea38815
Create Date: 2024-10-16 16:03:56.756185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc08064c981f'
down_revision = 'e646fea38815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concentration', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('concentration')

    # ### end Alembic commands ###
