"""Added type of data (exp or comp)

Revision ID: df8fe878c24f
Revises: bc08064c981f
Create Date: 2024-10-16 17:28:46.553951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8fe878c24f'
down_revision = 'bc08064c981f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.Enum('computational', 'experimental', name='measurementtype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###
