"""Added molecule

Revision ID: e1a7eb1b2835
Revises: 2bca53b12cda
Create Date: 2024-10-08 14:54:07.301924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1a7eb1b2835'
down_revision = '2bca53b12cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('composition', sa.String(length=100), nullable=False),
    sa.Column('wavelength', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('absortion', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('ecd', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molecule')
    # ### end Alembic commands ###
