"""Added real spec to mol

Revision ID: 1c4b03fcb9b6
Revises: 5a2da15b5a3d
Create Date: 2024-10-09 15:55:32.414649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c4b03fcb9b6'
down_revision = '5a2da15b5a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absortion_re', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('ecd_re', postgresql.ARRAY(sa.Float()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('ecd_re')
        batch_op.drop_column('absortion_re')

    # ### end Alembic commands ###
