"""Added 2d struc

Revision ID: 499778238f80
Revises: f1bd8380ce19
Create Date: 2024-11-15 10:38:06.995981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499778238f80'
down_revision = 'f1bd8380ce19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_d_struc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('two_d_struc')

    # ### end Alembic commands ###
