"""Edit to molecule

Revision ID: e8080ef33c02
Revises: dc4aedb057f6
Create Date: 2024-10-11 13:53:53.640250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8080ef33c02'
down_revision = 'dc4aedb057f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecule', schema=None) as batch_op:
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###
