"""Initial migration

Revision ID: f1bd8380ce19
Revises: 
Create Date: 2024-10-16 17:40:10.264340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1bd8380ce19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('affiliation', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('affiliation', sa.String(length=120), nullable=True),
    sa.Column('resgroup', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['resgroup'], ['researchgroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('molecule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('composition', sa.String(length=100), nullable=False),
    sa.Column('publication', sa.Text(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('pubchem_id', sa.Integer(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=False),
    sa.Column('iupac_name', sa.String(length=150), nullable=True),
    sa.Column('tool', postgresql.ENUM('computational', 'experimental', name='measurementtype'), nullable=False),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.Column('wavelength', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('absortion', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('ecd', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('absortion_re', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('ecd_re', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('molecule')
    op.drop_table('users')
    op.drop_table('researchgroup')
    # ### end Alembic commands ###
